// Generated by https://quicktype.io

export interface Employee {
  id: string;
  employee_name: string;
  employee_username: string;
  email: string;
  contact_numbers: ContactNumber[];
  adhar_number: string;
  pan_number: string;
  permanent_address: Address;
  residential_address: Address;
}

export interface ContactNumber {
  contact_number: number;
}

export interface Address {
  address_line_1: string;
  address_line_2: string;
  city: string;
  state: string;
  pincode: string;
}
