// Generated by https://quicktype.io

export interface Employee {
  id: string;
  employee_name: string;
  employee_username: string;
  email: string;
  employee_contact_numbers: EmployeeContactNumber[];
  address_checkbox: boolean;
  employee_adhaar_number: string;
  employee_pan_number: string;
  bank_name: string;
  bank_account_number: string;
  ifsc_code: string;
  provident_fund_account_number: string;
  residential_address: Address;
  permanent_address: Address;
}

export interface EmployeeContactNumber {
  contact_number: string;
}

export interface Address {
  address_line_1: null;
  address_line_2: null;
  city: null;
  state: null;
  pincode: null;
  meta: string;
}
