import { Address } from './employee';

// Generated by https://quicktype.io

export interface Lead {
  id: string;
  company_name: string;
  source: null;
  latitude: string;
  longitude: string;
  assigned_to: string;
  lead_status: null;
  product: null;
  contact_persons: ContactPerson[];
  company_info: CompanyInfo;
  social: Social;
  deal: Deal;
  source_info: SourceInfo;
  address: Address;
}

export interface CompanyInfo {
  company_employee_number: string;
  company_annual_revenue: string;
  company_website: string;
  company_phone: string;
  company_industry_type: null;
  company_business_type: null;
}

export interface ContactPerson {
  name: string;
  email: string;
  designation: string;
  primary_contact_number: string;
  secondary_contact_number: string;
}

export interface Deal {
  deal_name: string;
  deal_value: string;
  deal_expected_close_date: string;
  deal_product: null;
}

export interface Social {
  facebook_link: string;
  twitter_link: string;
  linkedin_link: string;
}

export interface SourceInfo {
  campaign: string;
  medium: string;
  keyword: string;
}
